### ISSUE TITLE
Compatibility Inquiry for Environment Setup

### ISSUE THREAD

**Issue by xtzhang0216** [levinthal/Pallatom#1]
Wonderful work!

I am currently trying to use your code on my setup, but I've encountered a compatibility issue. My system has CUDA 12.1, and I noticed that the provided environment with JAX 0.3.25 and Python 3.7 does not seem to be compatible with it.

Would it be possible for you to provide an environment that matches CUDA 12.1, or any guidance on how I can adjust the setup accordingly? Your assistance would be greatly appreciated!

Thanks in advance.

**Comment by guyujun** [comment]
If you encounter compatibility issues with higher CUDA versions, JAX 0.3.25, and Python 3.7, we offer the following solution using Python 3.10 and JAX with CUDA 12.6:

Create and activate a conda environment:

```bash
conda create --name pallatom python=3.10
conda activate pallatom
```
Install basic dependencies:

```bash
pip install biopython==1.79 dm-tree==0.1.8 chex==0.1.86 dm-haiku==0.0.12 dm-tree==0.1.8 immutabledict==2.0.0 ml-collections==0.1.0 numpy==1.24.3 pandas==2.0.3 scipy==1.11.1 tensorflow-cpu==2.16.1 rdkit einops tqdm
```

Install JAX with CUDA support:

```bash
pip install "jax[cuda]"==0.4.34 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by xtzhang0216** [comment]
Successfully run your code—thank you for making it available!

I am also interested in asking if you might consider open-sourcing code for binder design in the future. I believe that the atom-level model designed to bind with the target would enable excellent stacking with the target, potentially resulting in high binding affinity.

Thank you again for your incredible work!
